[package]
name = "blockchain"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10.8"
hex = "0.4.3"
num-bigint = "0.4.4"
sled = "0.34.7"
thiserror = "1.0.59"
ripemd = "0.1.3"
bs58 = "0.5.1"
serde = "1.0.198"
serde_derive = "1.0.198"
bincode = "1.3.3"
p256 = "0.13.2"
rand = "0.8.5"
